name: PR build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Initiate error tracking
        uses: spring-projects/track-build-errors-action@v0.01
        with:
          job-name: "initiate-error-tracking"
      - name: Export errors file
        uses: actions/upload-artifact@v2
        with:
          name: errors
          path: job-initiate-error-tracking.txt
      - name: Track error step
        uses: spring-projects/track-build-errors-action@v0.01
#        if: ${{ failure() }}
        with:
          job-name: ${{ github.job }}
      - name: Export errors file
        uses: actions/upload-artifact@v2
#        if: ${{ failure() }}
        with:
          name: errors
          path: job-${{ github.job }}.txt
  other_build:
    name: Build 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Track error step
        uses: spring-projects/track-build-errors-action@v0.01
        if: ${{ failure() }}
        with:
          job-name: ${{ github.job }}
      - name: Export errors file
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: errors
          path: job-${{ github.job }}.txt
  hello_world_job:
    runs-on: ubuntu-latest
    needs: [build, other_build]
    name: Test external action
    steps:
      - uses: actions/checkout@v2
      - name: Pwd
        run: |
          echo "You are in this directory:"
          pwd
          ls
      - name: Track error step
        uses: spring-projects/track-build-errors-action@v0.01
        if: ${{ failure() }}
        with:
          job-name: ${{ github.job }}
      - name: Export errors file
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: errors
          path: job-${{ github.job }}.txt
  notify_result:
    name: Check for failures
    needs: [build, other_build, hello_world_job]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download errors folder
        uses: actions/download-artifact@v2
        with:
          name: errors
      - name: Send Slack message
        id: send-slack-message
        uses: spring-projects/notify-slack-errors-action@v0.01
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          branch-name: ${{ github.ref }}
          commit-sha: ${{ github.sha }}
          commit-owner: ${{ github.actor }}
          repo-name: ${{ github.repository }}
          run-id: ${{ github.run_id }}
