name: PR build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: '14'
          architecture: x64
          secret_color: ${{ secrets.COLOR }}
        env:
          FAV_WORD: ${{ secrets.FAVORITE_WORD }}
      - name: Spill your secrets!
        run: echo "here are my secrets $FAV_WORD"
#      - name: Maven Package
#        run: mvn -B clean package -DskipTests
#      - name: Maven Verify
#        run: mvn -B clean verify


