name: Sample build

on:
  push:
    branches:
      - master

jobs:
  initiate_error_tracking:
    name: Initiate job-level error tracking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Initiate error tracking
        uses: spring-projects/track-build-errors-action@v0.01
        with:
          job-name: "initiate-error-tracking"
      - name: Export errors file
        uses: actions/upload-artifact@v2
        with:
          name: errors
          path: job-initiate-error-tracking.txt
  sample_job_1:
    name: Sample job 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sample job step
        run: echo "This is a sample job 1 step"
      - name: Track error step
        uses: spring-projects/track-build-errors-action@v0.01
        if: ${{ failure() }}
        with:
          job-name: ${{ github.job }}
      - name: Export errors file
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: errors
          path: job-${{ github.job }}.txt
  sample_job_2:
    name: Sample job 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sample job step
        run: echo "This is a sample job 2 step"
      - name: Track error step
        uses: spring-projects/track-build-errors-action@v0.01
        if: ${{ failure() }}
        with:
          job-name: ${{ github.job }}
      - name: Export errors file
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: errors
          path: job-${{ github.job }}.txt
  sample_job_3:
    name: Sample job 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sample job step
        run: echo "This is a sample job 3 step"
      - name: Track error step
        uses: spring-projects/track-build-errors-action@v0.01
        if: ${{ failure() }}
        with:
          job-name: ${{ github.job }}
      - name: Export errors file
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: errors
          path: job-${{ github.job }}.txt
  notify_result:
    name: Check for failures
    needs: [initiate_error_tracking, sample_job_1, sample_job_2, sample_job_3]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download errors folder
        uses: actions/download-artifact@v2
        with:
          name: errors
      - name: Send Slack message
        uses: spring-projects/notify-slack-errors-action@v0.01
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          branch-name: ${{ github.ref }}
          commit-sha: ${{ github.sha }}
          commit-owner: ${{ github.actor }}
          repo-name: ${{ github.repository }}
          run-id: ${{ github.run_id }}