name: PR build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Track error step
        id: track-errors
        uses: elliedori/hello-world-js-action@v1.27
        with:
          job-name: ${{ github.job }}
      - name: Pwd
        run: |
          echo "You are in this directory:"
          pwd
          ls
      - name: Export errors file
        uses: actions/upload-artifact@v2
        with:
          name: errors
          path: job-${{ github.job }}.txt
  other_build:
    name: Build 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Track error step
        id: track-errors
        uses: elliedori/hello-world-js-action@v1.27
        with:
          job-name: ${{ github.job }}
      - name: Pwd
        run: |
          echo "You are in this directory:"
          pwd
          ls
      - name: Export errors file
        uses: actions/upload-artifact@v2
        with:
          name: errors
          path: job-${{ github.job }}.txt
  hello_world_job:
    runs-on: ubuntu-latest
    needs: [build, other_build]
    name: Test external action
    steps:
      - uses: actions/checkout@v2
      - name: Pwd
        run: |
          echo "You are in this directory:"
          pwd
          ls
      - name: Track error step
        id: track-errors
        uses: elliedori/hello-world-js-action@v1.27
        with:
          job-name: ${{ github.job }}
      - name: Check for existing file
        run: |
          echo "Does this include action-output?:"
          pwd
          ls
      - name: Export errors file
        uses: actions/upload-artifact@v2
        with:
          name: errors
          path: job-${{ github.job }}.txt
  notify_result:
    name: Check for failures
    needs: [build, other_build, hello_world_job]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download errors folder
        uses: actions/download-artifact@v2
        with:
          name: errors
      - name: Alert Slack on build failure
        run: |
          ls
          head job-hello_world_job.txt
          head job-build.txt
          cat job-*.txt > results.txt
          results="$(cat results.txt)"
          echo Results are $results
          jobFilesCount=$(ls . | grep 'job-.*\.txt' | wc -l)
          (( $jobFilesCount > 1 )) && echo Sending Slack message... || echo Slack message not sent, no errors to report
      - name: Send Slack message
        id: send-slack-message
        uses: elliedori/slack-errors-github-action@v0.1
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}